name: CCLab-CI

on:
  pull_request:
  push:

jobs:
  scipack-ci:
    name: scipack integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-selenium
      - name: Build the new scipack image
        run: docker build -t scipack .
      - name: Run the new scipack image
        run: |
          rm -rf /tmp/share
          mkdir /tmp/share
          docker run -v /tmp/share:/home/cclab/share --name SCIPACK --rm -d -p 127.0.0.1:8787:8787 -p 127.0.0.1:8888:8888 -e DISABLE_AUTH=true scipack
          docker ps |grep -q SCIPACK
      - name: Chrome tests
        run: |
          pytest -srA --driver=chrome
      - name: Firefox tests
        run: |
          sudo rm -f /tmp/share/Untitled.ipynb
          pytest -srA --driver=chrome
